version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-development
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    ports:
      - "${WEB_PORT:-8000}:8000"
    environment:
      MONGO_URL: mongodb://db:27017/mern-starter

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata_dev:/data/db

volumes:
  dbdata_dev:
